debug: true
server:
  host: "0.0.0.0"
  port: 9000

sst:
  aesKey: "Jzw8C%E/y,FSK4<}n?"
  # service name, case-insensitive
  serviceName: "sample"

log:
  # line -> console log with color
  # json -> console log, but json structure
  format: "line"
  # trace / debug / info / warn / error / fatal / panic / disabled
  level: "trace"
